/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SnowEffect {
        "color": string;
        "flakes": number;
        "speed": number;
    }
}
declare global {
    interface HTMLSnowEffectElement extends Components.SnowEffect, HTMLStencilElement {
    }
    var HTMLSnowEffectElement: {
        prototype: HTMLSnowEffectElement;
        new (): HTMLSnowEffectElement;
    };
    interface HTMLElementTagNameMap {
        "snow-effect": HTMLSnowEffectElement;
    }
}
declare namespace LocalJSX {
    interface SnowEffect {
        "color"?: string;
        "flakes"?: number;
        "speed"?: number;
    }
    interface IntrinsicElements {
        "snow-effect": SnowEffect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "snow-effect": LocalJSX.SnowEffect & JSXBase.HTMLAttributes<HTMLSnowEffectElement>;
        }
    }
}
